////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using GenerativeObjects.Practices.ORMSupportClasses;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Solid.Data.DataObjects;
using Solid.Data.DataObjects.Factories;
 

namespace Solid.Data.DataObjects.Factories
{
    public class VisitedPlaceFactory : IDataObjectFactory<VisitedPlaceDataObject> 
    {
        public object CreateDataSetContainer(VisitedPlaceDataObject entity)
        {
            return new VisitedPlaceContainer(entity);
        }

        public object CreateDataSetContainer(DataObjectCollection<VisitedPlaceDataObject> entityCollection)
        {
            return new VisitedPlaceCollectionContainer(entityCollection);
        }

        public VisitedPlaceDataObject CreateDataObject(IEnumerable<string> pks)
        {
            var pksAsArray = pks.ToArray();

            if (pksAsArray.Length != 2)
                throw new ApplicationException("CreateObject - VisitedPlace - Wrong number of PKs");

			System.Guid id;

			try 
			{
				id = Guid.Parse(pksAsArray[0]);           
			}
			catch(Exception)
			{
                throw new ApplicationException("Wrong pk type for VisitedPlace.Id - should be System.Guid");
			}

			System.String userprofileuri;

			try 
			{
				userprofileuri = pksAsArray[1];           
			}
			catch(Exception)
			{
                throw new ApplicationException("Wrong pk type for VisitedPlace.UserProfileUri - should be System.String");
			}

                         
            var result = new VisitedPlaceDataObject(id);
			result.UserProfileUri = userprofileuri;
            return result;
        }

        public VisitedPlaceDataObject DeserializeFromContainer(string jsonstring, JsonSerializerSettings settings)
        {
            var container = JsonConvert.DeserializeObject<VisitedPlaceContainer>(jsonstring, settings);

			if(container == null)
			 return null;

			var result = container.ExtractVisitedPlace();

			// result can legitimately be null, because e.g. the dataset may contain an instance related to the main/primary entity, but not the main/primary entity itself
			// In this case we create an 'empty' instance of the main/primary entity and attach + reconstruct the dataset
            if (result == null)
            {
                result = new VisitedPlaceDataObject(container.PrimaryKey) { IsNew = false, IsDirty = false };
                result.ObjectsDataSet = container.ObjectsDataSet;

				// Sync the dataset 
				result.ObjectsDataSet.EnsureInitialized();
				result.ObjectsDataSet.ReconstructIndexes();
            }

			result.OnDeserialized();

			return result;
		}

		public VisitedPlaceDataObject DeserializeObject(string jsonstring, JsonSerializerSettings settings)
        {	
			var result = JsonConvert.DeserializeObject<VisitedPlaceDataObject>(jsonstring, settings);

			if(result == null)
			 return null;

			result.OnDeserialized();
			return result;
		}
	}
}