////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using GenerativeObjects.Practices.ORMSupportClasses;
using GenerativeObjects.Practices.DependencyInjection;
using GenerativeObjects.Practices.Logging;
using GenerativeObjects.Practices.ExceptionHandling;
using System.Collections.Concurrent;
using GenerativeObjects.Practices.LayerSupportClasses;
using Unity;


namespace Solid.Data.DataObjects
{
	[JsonObject(MemberSerialization.OptIn)]
	public class GOGroupRoleObjectsDataSet : ObjectsDataSetBase
	{
        #region fields

        private ObjectsDataSet _rootObjectDataSet;
		private ILogEngine _logEngine = ApplicationSettings.Container.Resolve<ILogEngine>();

		// Mapping between entity primary key and data set objects collection internal id
		private ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.String>, int> _gOGroupRoleObjectInternalIds = new ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.String>, int>();
		
		// Collection holding all GOGroupRole objects for current dataset
		private ConcurrentDictionary< int, GOGroupRoleDataObject> _gOGroupRoleObjects = new ConcurrentDictionary< int, GOGroupRoleDataObject>();

		// Temp list of merged data objects - required for merge finalization
		private ConcurrentQueue<GOGroupRoleDataObject> _mergedDataObjects;

		private ConcurrentQueue<GOGroupRoleDataObject> MergedDataObjects 
		{
			get
			{
				if (_mergedDataObjects == null)
					_mergedDataObjects = new ConcurrentQueue<GOGroupRoleDataObject>();
					
				return _mergedDataObjects;
			}
		}
		
		private void ClearMergedDataObjects()
		{
			_mergedDataObjects = null;
		}

        #endregion

		#region properties

        public ObjectsDataSet RootObjectDataSet
        {
            get { return _rootObjectDataSet; }
            set
            {
                _rootObjectDataSet = value;
            }
        }
		
		// Mapping between entity primary key and data set objects collection internal id
		public ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.String>, int> GOGroupRoleObjectInternalIds
		{ 
			get { return _gOGroupRoleObjectInternalIds; }
			set { _gOGroupRoleObjectInternalIds = value; }
		}
		
		// Collection holding all GOGroupRole objects for current dataset
		[JsonProperty(DefaultValueHandling  = DefaultValueHandling.Ignore)]
		public ConcurrentDictionary< int, GOGroupRoleDataObject> GOGroupRoleObjects
		{ 
			get { return _gOGroupRoleObjects; }
			set { _gOGroupRoleObjects = value; }
		}
		
		// Index to quickly find all GOGroupRole with a given group foreign key
		public ConcurrentDictionary<System.String, List<int>> Group_FKIndex = new ConcurrentDictionary<System.String, List<int>>();
		
 
		// Index to quickly find all GOGroupRole with a given role foreign key
		public ConcurrentDictionary<System.String, List<int>> Role_FKIndex = new ConcurrentDictionary<System.String, List<int>>();
		
 
		
		#endregion
		
		#region initialization

        public GOGroupRoleObjectsDataSet(ObjectsDataSet rootObjectDataSet)
        {
            _rootObjectDataSet = rootObjectDataSet;
        }

        #endregion

		#region IObjectsDataSet implementation

		public override IObjectsDataSet Clone()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet Clone(IObjectsDataSet rootDataSet)
		{
			var clone = new GOGroupRoleObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.GOGroupRoleObjects)
			{
                var cloneObject = (GOGroupRoleDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOGroupRoleObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.GOGroupRoleObjectInternalIds)
			{
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOGroupRoleObjectInternalIds.TryAdd(keyValue.Key.Clone(), keyValue.Value);
				}
			}

			foreach(var fkKeyValue in this.Group_FKIndex)
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = clone.Group_FKIndex.TryAdd(fkKeyValue.Key, new List<int>());
				}

				foreach (var pk in fkKeyValue.Value)
				{
					clone.Group_FKIndex[fkKeyValue.Key].Add(pk);
				}
			}

			foreach(var fkKeyValue in this.Role_FKIndex)
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = clone.Role_FKIndex.TryAdd(fkKeyValue.Key, new List<int>());
				}

				foreach (var pk in fkKeyValue.Value)
				{
					clone.Role_FKIndex[fkKeyValue.Key].Add(pk);
				}
			}

			
			return clone;
		}

		public override IObjectsDataSet CloneDirtyObjects()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet CloneDirtyObjects(IObjectsDataSet rootDataSet)
		{
			var clone = new GOGroupRoleObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.GOGroupRoleObjects.Where(o => o.Value.IsDirty || o.Value.IsMarkedForDeletion))
			{
                var cloneObject = (GOGroupRoleDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				while (!completed)
				{
					 completed = clone.GOGroupRoleObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.GOGroupRoleObjectInternalIds
				.Where(o => this.GOGroupRoleObjects[o.Value].IsDirty || this.GOGroupRoleObjects[o.Value].IsMarkedForDeletion))
			{
				completed = false;
				
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOGroupRoleObjectInternalIds.TryAdd(keyValue.Key.Clone(), keyValue.Value);
				}
			}
			
			// CloneDirtyObjects is used to pass only dirty objects to server to save changes. Since indexes are not serialized, no need to clone them
            return clone;
		}

		public override IEnumerable<IDataObject> GetAllObjects()
		{
			foreach(var gOGroupRole in GOGroupRoleObjects.Values)
			{
				yield return gOGroupRole; 
			}				
		}

	    public override void AddObject(IDataObject objectToAdd, bool replaceIfExists)
        {
			var existingObject = GetObject(objectToAdd);
            if (!replaceIfExists && existingObject != null)
                throw new PulpException("Object already exists");

			int newInternalId; 
			
            if (existingObject != null)
			{
                //RemoveObject(existingObject);
				if(existingObject.InternalObjectId == null)
				{
					_logEngine.LogError("Error while trying to Add Object to the GOGroupRoleObjectsDataSet", "The object you are trying to add doesn't have an InternalObjectId", "GOGroupRoleObjectsDataSet", null);
					throw new PulpException("Error while trying to add an object to the dataset without InternalObjectId");
				}
                newInternalId = (int) existingObject.InternalObjectId;
                objectToAdd.InternalObjectId = newInternalId;
				existingObject.CopyValuesFrom(objectToAdd, false);
			}
			else
			{
            	newInternalId = GetNextNewInternalObjectId();
				objectToAdd.InternalObjectId = newInternalId;

				 var completed = false;
				 var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOGroupRoleObjects.TryAdd(newInternalId, (GOGroupRoleDataObject)objectToAdd);
				}
			}
			
			if (!objectToAdd.IsNew && existingObject == null)
			{
                //The following if should not be necessary...
				var completed = false;
				if (GOGroupRoleObjectInternalIds.ContainsKey(((GOGroupRoleDataObject)objectToAdd).PrimaryKeysCollection))
				{
					int value;
					var count2 = 0;
					while (!completed && count2++ < 15)
					{
						completed = GOGroupRoleObjectInternalIds.TryRemove(((GOGroupRoleDataObject)objectToAdd).PrimaryKeysCollection, out value);
					}
				}

				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOGroupRoleObjectInternalIds.TryAdd(((GOGroupRoleDataObject)objectToAdd).PrimaryKeysCollection, newInternalId);
				}
			}
			// Update relations including platform as "many" side or "one" side , pk side for one to one relations
			if((objectToAdd as GOGroupRoleDataObject) == null)
			{
				_logEngine.LogError("Unable to Add an object which is null", "Unable to add an object which is null", "GOGroupRoleDataObject", null);
				throw new PulpException("Unexpected Error: Unable to Add an object which is Null.");
			}

			// Update the Group FK Index 
			if ((objectToAdd as GOGroupRoleDataObject).GOGroupName != null)
			{
			if (!Group_FKIndex.ContainsKey((objectToAdd as GOGroupRoleDataObject).GOGroupName))
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = Group_FKIndex.TryAdd((objectToAdd as GOGroupRoleDataObject).GOGroupName, new List<int>());
				}
			}
				
			if (!Group_FKIndex[(objectToAdd as GOGroupRoleDataObject).GOGroupName].Contains(newInternalId))
				Group_FKIndex[(objectToAdd as GOGroupRoleDataObject).GOGroupName].Add(newInternalId);

            GOGroupDataObject relatedGroup;
            if ((objectToAdd as GOGroupRoleDataObject)._group_NewObjectId != null)
            {
                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject() { IsNew = true, InternalObjectId = (objectToAdd as GOGroupRoleDataObject)._group_NewObjectId });
            }
            else
            {
                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject((objectToAdd as GOGroupRoleDataObject).GOGroupName) { IsNew = false });
            }

			if (relatedGroup != null && this.RootObjectDataSet.NotifyChanges)
                relatedGroup.NotifyPropertyChanged("GroupRoleItems", new SeenObjectCollection());
			
			}
	 
			// Update the Role FK Index 
			if ((objectToAdd as GOGroupRoleDataObject).GORoleName != null)
			{
			if (!Role_FKIndex.ContainsKey((objectToAdd as GOGroupRoleDataObject).GORoleName))
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = Role_FKIndex.TryAdd((objectToAdd as GOGroupRoleDataObject).GORoleName, new List<int>());
				}
			}
				
			if (!Role_FKIndex[(objectToAdd as GOGroupRoleDataObject).GORoleName].Contains(newInternalId))
				Role_FKIndex[(objectToAdd as GOGroupRoleDataObject).GORoleName].Add(newInternalId);

            GORoleDataObject relatedRole;
            if ((objectToAdd as GOGroupRoleDataObject)._role_NewObjectId != null)
            {
                relatedRole = _rootObjectDataSet.GetObject(new GORoleDataObject() { IsNew = true, InternalObjectId = (objectToAdd as GOGroupRoleDataObject)._role_NewObjectId });
            }
            else
            {
                relatedRole = _rootObjectDataSet.GetObject(new GORoleDataObject((objectToAdd as GOGroupRoleDataObject).GORoleName) { IsNew = false });
            }

			if (relatedRole != null && this.RootObjectDataSet.NotifyChanges)
                relatedRole.NotifyPropertyChanged("GroupRoleItems", new SeenObjectCollection());
			
			}
	 
		
		}

        public override void RemoveObject(IDataObject objectToRemove)
        {
            if (GOGroupRoleObjects == null)
                return;
			bool completed;			
			int? objectToRemoveInternalId;
			
			if((objectToRemove as GOGroupRoleDataObject) == null)
			{
				_logEngine.LogError("Unable to remove null object", "The object you are trying to remove is null", "GOGroupRoleObjectsDataSet.RemoveObject", null);
				throw new PulpException("Unable to remove Null Object.");
			}

			if (objectToRemove.IsNew)
				objectToRemoveInternalId = objectToRemove.InternalObjectId;
			else
				objectToRemoveInternalId = GOGroupRoleObjectInternalIds.ContainsKey((objectToRemove as GOGroupRoleDataObject).PrimaryKeysCollection) ? (int?) GOGroupRoleObjectInternalIds[(objectToRemove as GOGroupRoleDataObject).PrimaryKeysCollection] : null;
				
			if (objectToRemoveInternalId != null)
			{
				GOGroupRoleDataObject value;
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOGroupRoleObjects.TryRemove((int)objectToRemoveInternalId, out value);
				}

                // Reinit InternalObjectId only if the object to remove is part of the current dataset
				if (ReferenceEquals(objectToRemove.ObjectsDataSet, this._rootObjectDataSet))
					objectToRemove.InternalObjectId = null;
				
				if (!objectToRemove.IsNew)
				{
					int idvalue;
					completed = false;
					count = 0;
					while (!completed && count++ < 15)
					{
						completed = GOGroupRoleObjectInternalIds.TryRemove((objectToRemove as GOGroupRoleDataObject).PrimaryKeysCollection, out idvalue);
					}
				}
				
			// Delete the Group FK Index 
				if ((objectToRemove as GOGroupRoleDataObject).GOGroupName != null)
				{
				if (Group_FKIndex.ContainsKey((objectToRemove as GOGroupRoleDataObject).GOGroupName) && Group_FKIndex[(objectToRemove as GOGroupRoleDataObject).GOGroupName].Contains((int)objectToRemoveInternalId))
				{
					Group_FKIndex[(objectToRemove as GOGroupRoleDataObject).GOGroupName].Remove((int)objectToRemoveInternalId);

					if (!Group_FKIndex[(objectToRemove as GOGroupRoleDataObject).GOGroupName].Any())
					{
						List<int> outvalue;
						var iscompleted = false;
						var count2 = 0;
						while (!iscompleted  && count2++ < 15)
						{
							iscompleted = Group_FKIndex.TryRemove((objectToRemove as GOGroupRoleDataObject).GOGroupName, out outvalue);
						}
					}
				}
				
				GOGroupDataObject relatedGroup;
	            if ((objectToRemove as GOGroupRoleDataObject)._group_NewObjectId != null)
	            {
	                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject() { IsNew = true, InternalObjectId = (objectToRemove as GOGroupRoleDataObject)._group_NewObjectId });
	            }
	            else
	            {
	                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject((objectToRemove as GOGroupRoleDataObject).GOGroupName) { IsNew = false });
	            }

	            if (relatedGroup != null && this.RootObjectDataSet.NotifyChanges)
	                relatedGroup.NotifyPropertyChanged("GroupRoleItems", new SeenObjectCollection());
				
				}
		 
			// Delete the Role FK Index 
				if ((objectToRemove as GOGroupRoleDataObject).GORoleName != null)
				{
				if (Role_FKIndex.ContainsKey((objectToRemove as GOGroupRoleDataObject).GORoleName) && Role_FKIndex[(objectToRemove as GOGroupRoleDataObject).GORoleName].Contains((int)objectToRemoveInternalId))
				{
					Role_FKIndex[(objectToRemove as GOGroupRoleDataObject).GORoleName].Remove((int)objectToRemoveInternalId);

					if (!Role_FKIndex[(objectToRemove as GOGroupRoleDataObject).GORoleName].Any())
					{
						List<int> outvalue;
						var iscompleted = false;
						var count2 = 0;
						while (!iscompleted  && count2++ < 15)
						{
							iscompleted = Role_FKIndex.TryRemove((objectToRemove as GOGroupRoleDataObject).GORoleName, out outvalue);
						}
					}
				}
				
				GORoleDataObject relatedRole;
	            if ((objectToRemove as GOGroupRoleDataObject)._role_NewObjectId != null)
	            {
	                relatedRole = _rootObjectDataSet.GetObject(new GORoleDataObject() { IsNew = true, InternalObjectId = (objectToRemove as GOGroupRoleDataObject)._role_NewObjectId });
	            }
	            else
	            {
	                relatedRole = _rootObjectDataSet.GetObject(new GORoleDataObject((objectToRemove as GOGroupRoleDataObject).GORoleName) { IsNew = false });
	            }

	            if (relatedRole != null && this.RootObjectDataSet.NotifyChanges)
	                relatedRole.NotifyPropertyChanged("GroupRoleItems", new SeenObjectCollection());
				
				}
		 
			}		
		}

		public override TDataObject GetObject<TDataObject>(Type objectBaseType, int internalObjectId)
        {
            return GOGroupRoleObjects.ContainsKey(internalObjectId) ? GOGroupRoleObjects[internalObjectId] as TDataObject : null;
        }

        public override TDataObject GetObject<TDataObject>(TDataObject objectToGet)
        {
			int? objectToGetInternalId;
			
			if (objectToGet.IsNew)
				objectToGetInternalId = objectToGet.InternalObjectId;
			else
			{
				if((objectToGet as GOGroupRoleDataObject) == null)
				{
					_logEngine.LogError("Unable to get value which value is null", "The object you are trying to get doesn't have a value", "GOGroupRoleObjectsDataSet", null);
					throw new PulpException("Unable to get an element which value is null.");
				}
				objectToGetInternalId = GOGroupRoleObjectInternalIds.ContainsKey((objectToGet as GOGroupRoleDataObject).PrimaryKeysCollection) ? (int?) GOGroupRoleObjectInternalIds[(objectToGet as GOGroupRoleDataObject).PrimaryKeysCollection] : null;
			}
			if (objectToGetInternalId != null)
			{
				return GOGroupRoleObjects.ContainsKey((int)objectToGetInternalId) ? GOGroupRoleObjects[(int)objectToGetInternalId] as TDataObject : null;
			}

			return null;
        }
		
        public override IEnumerable<IDataObject> GetObjectsMarkedForDeletion()
        {
			return GOGroupRoleObjects.Values.Where(c => c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		public override IEnumerable<IDataObject> GetObjectsOutOfGraph()
        {
			return GOGroupRoleObjects.Values.Where(c => !c.IncludedInGraph && !c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		
		public IEnumerable<GOGroupRoleDataObject> GetGroupRoleItemsForGroup(GOGroupDataObject groupInstance) 
		{
			if (groupInstance.IsNew)
            {
			
              return GOGroupRoleObjects.Where(o => o.Value._group_NewObjectId != null && o.Value._group_NewObjectId == groupInstance.InternalObjectId).Select(o => o.Value);
			}
				
			if (Group_FKIndex.ContainsKey(groupInstance.Name))
			{
				return Group_FKIndex[groupInstance.Name].Where(e => GOGroupRoleObjects.ContainsKey(e)).Select(e => GOGroupRoleObjects[e]);
			}
			
			return new DataObjectCollection<GOGroupRoleDataObject>();
		}
		 
		
		public IEnumerable<GOGroupRoleDataObject> GetGroupRoleItemsForRole(GORoleDataObject roleInstance) 
		{
			if (roleInstance.IsNew)
            {
			
              return GOGroupRoleObjects.Where(o => o.Value._role_NewObjectId != null && o.Value._role_NewObjectId == roleInstance.InternalObjectId).Select(o => o.Value);
			}
				
			if (Role_FKIndex.ContainsKey(roleInstance.Name))
			{
				return Role_FKIndex[roleInstance.Name].Where(e => GOGroupRoleObjects.ContainsKey(e)).Select(e => GOGroupRoleObjects[e]);
			}
			
			return new DataObjectCollection<GOGroupRoleDataObject>();
		}
		 

        public override DataObjectCollection<TDataObject> GetRelatedObjects<TDataObject>(IDataObject rootObject, string relationName)
        {
 
 
			return null;
		}
		
        public override void Merge(IObjectsDataSet dataSetToMerge, bool updateOrginalInternalId)
        {
			var GOGroupRoleDataSet = dataSetToMerge as GOGroupRoleObjectsDataSet;
			if(GOGroupRoleDataSet == null)
			{
				throw new PulpException("Unable to merge the current DataSet with null");
			}
            foreach (var item in GOGroupRoleDataSet.GOGroupRoleObjects.Values)
            {
                var oldInternalId = item.InternalObjectId;

				var objectToMerge = item.Clone(false);
                objectToMerge.InternalObjectId = null;
                objectToMerge.ObjectsDataSet = this._rootObjectDataSet;
				
				objectToMerge.IsMarkedForDeletion = item.IsMarkedForDeletion;
                
				_rootObjectDataSet.AddOrReplaceObject(objectToMerge);
                var newInternalId = objectToMerge.InternalObjectId;
                if (updateOrginalInternalId)
                    item.InternalObjectId = newInternalId;

				if (oldInternalId != null && !_rootObjectDataSet.DatasetMergingInternalIdMapping.ContainsKey((int) oldInternalId))
				{
					if(newInternalId == null)
					{
						_logEngine.LogError("Unable to merge elements in DataSet without InternalId", "The Element you are trying to merge doesn't have an internalId", "GOGroupRoleObjectsDataSet", null);
						throw new PulpException("Unable to merge elements in dataset without InternalId");
					}
					var completed = false;
					var count = 0;
					while (!completed && count++ < 15)
					{
						completed = _rootObjectDataSet.DatasetMergingInternalIdMapping.TryAdd((int) oldInternalId, (int) newInternalId);
					}
				}

				MergedDataObjects.Enqueue(objectToMerge as GOGroupRoleDataObject);
            }
        }
		
		public override void FinalizeMerge()
		{
			foreach(var mergedObject in MergedDataObjects)
			{
				mergedObject.UpdateRelatedInternalIds(_rootObjectDataSet.DatasetMergingInternalIdMapping);
			}
			
			ClearMergedDataObjects();
		}

		public override void ReconstructIndexes()
		{
			// Reconstruct the Group FK Index 
			Group_FKIndex = new ConcurrentDictionary< System.String, List<int>>();
				
			foreach (var item in GOGroupRoleObjects.Values)
			{
				if (item.GOGroupName == null) 
					continue;				
				
				if (item.IsMarkedForDeletion)
					continue;

				var fk = item.GOGroupName;	

				if (!Group_FKIndex.ContainsKey(fk))
				{
					var iscompleted = false;
					var count2 = 0;
					while (!iscompleted && count2++ < 15)
					{
						iscompleted = Group_FKIndex.TryAdd(fk, new List<int>());
					}
				}
				if(item.InternalObjectId == null)
				{
					_logEngine.LogError("Unable to reconstruct indexes.", "An error occured while trying to reconstruct indexes", "GOGroupRoleObjectsDataSet", null);
					throw new PulpException("Unable to reconstruct indexes.");
				}
					
				Group_FKIndex[fk].Add((int)item.InternalObjectId);
			}			
		 
			// Reconstruct the Role FK Index 
			Role_FKIndex = new ConcurrentDictionary< System.String, List<int>>();
				
			foreach (var item in GOGroupRoleObjects.Values)
			{
				if (item.GORoleName == null) 
					continue;				
				
				if (item.IsMarkedForDeletion)
					continue;

				var fk = item.GORoleName;	

				if (!Role_FKIndex.ContainsKey(fk))
				{
					var iscompleted = false;
					var count2 = 0;
					while (!iscompleted && count2++ < 15)
					{
						iscompleted = Role_FKIndex.TryAdd(fk, new List<int>());
					}
				}
				if(item.InternalObjectId == null)
				{
					_logEngine.LogError("Unable to reconstruct indexes.", "An error occured while trying to reconstruct indexes", "GOGroupRoleObjectsDataSet", null);
					throw new PulpException("Unable to reconstruct indexes.");
				}
					
				Role_FKIndex[fk].Add((int)item.InternalObjectId);
			}			
		 
		}

		#endregion

		#region private methods
		
		private int GetNextNewInternalObjectId()
		{
			int newInternalId = _rootObjectDataSet.GetNextNewObjectId();

			// With business entity hierarchies I was seeing objects in dataset with same internal Id. Something to do with PK being the same for entities in hierarchy perhaps?
			// Anyway, it's dangeroud because means LoadParentEntity() can get stuck in infinite loop if it finds 'itself' as parent of iteself because of the internal Ids.
			// Ensure newInternalId not already in use
			while (GOGroupRoleObjectInternalIds.Values.Contains(newInternalId))
			{
				newInternalId = _rootObjectDataSet.GetNextNewObjectId();
			}

			return newInternalId;
		}

		#endregion

	}	
}