////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using GenerativeObjects.Practices.ORMSupportClasses;
using GenerativeObjects.Practices.DependencyInjection;
using GenerativeObjects.Practices.Logging;
using GenerativeObjects.Practices.ExceptionHandling;
using System.Collections.Concurrent;
using GenerativeObjects.Practices.LayerSupportClasses;
using Unity;


namespace Solid.Data.DataObjects
{
	[JsonObject(MemberSerialization.OptIn)]
	public class GOUserGroupObjectsDataSet : ObjectsDataSetBase
	{
        #region fields

        private ObjectsDataSet _rootObjectDataSet;
		private ILogEngine _logEngine = ApplicationSettings.Container.Resolve<ILogEngine>();

		// Mapping between entity primary key and data set objects collection internal id
		private ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.Guid>, int> _gOUserGroupObjectInternalIds = new ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.Guid>, int>();
		
		// Collection holding all GOUserGroup objects for current dataset
		private ConcurrentDictionary< int, GOUserGroupDataObject> _gOUserGroupObjects = new ConcurrentDictionary< int, GOUserGroupDataObject>();

		// Temp list of merged data objects - required for merge finalization
		private ConcurrentQueue<GOUserGroupDataObject> _mergedDataObjects;

		private ConcurrentQueue<GOUserGroupDataObject> MergedDataObjects 
		{
			get
			{
				if (_mergedDataObjects == null)
					_mergedDataObjects = new ConcurrentQueue<GOUserGroupDataObject>();
					
				return _mergedDataObjects;
			}
		}
		
		private void ClearMergedDataObjects()
		{
			_mergedDataObjects = null;
		}

        #endregion

		#region properties

        public ObjectsDataSet RootObjectDataSet
        {
            get { return _rootObjectDataSet; }
            set
            {
                _rootObjectDataSet = value;
            }
        }
		
		// Mapping between entity primary key and data set objects collection internal id
		public ConcurrentDictionary< IdentifyingFieldsCollection<System.String,System.Guid>, int> GOUserGroupObjectInternalIds
		{ 
			get { return _gOUserGroupObjectInternalIds; }
			set { _gOUserGroupObjectInternalIds = value; }
		}
		
		// Collection holding all GOUserGroup objects for current dataset
		[JsonProperty(DefaultValueHandling  = DefaultValueHandling.Ignore)]
		public ConcurrentDictionary< int, GOUserGroupDataObject> GOUserGroupObjects
		{ 
			get { return _gOUserGroupObjects; }
			set { _gOUserGroupObjects = value; }
		}
		
		// Index to quickly find all GOUserGroup with a given group foreign key
		public ConcurrentDictionary<System.String, List<int>> Group_FKIndex = new ConcurrentDictionary<System.String, List<int>>();
		
 
		// Index to quickly find all GOUserGroup with a given user foreign key
		public ConcurrentDictionary<System.Guid, List<int>> User_FKIndex = new ConcurrentDictionary<System.Guid, List<int>>();
		
 
		
		#endregion
		
		#region initialization

        public GOUserGroupObjectsDataSet(ObjectsDataSet rootObjectDataSet)
        {
            _rootObjectDataSet = rootObjectDataSet;
        }

        #endregion

		#region IObjectsDataSet implementation

		public override IObjectsDataSet Clone()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet Clone(IObjectsDataSet rootDataSet)
		{
			var clone = new GOUserGroupObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.GOUserGroupObjects)
			{
                var cloneObject = (GOUserGroupDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOUserGroupObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.GOUserGroupObjectInternalIds)
			{
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOUserGroupObjectInternalIds.TryAdd(keyValue.Key.Clone(), keyValue.Value);
				}
			}

			foreach(var fkKeyValue in this.Group_FKIndex)
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = clone.Group_FKIndex.TryAdd(fkKeyValue.Key, new List<int>());
				}

				foreach (var pk in fkKeyValue.Value)
				{
					clone.Group_FKIndex[fkKeyValue.Key].Add(pk);
				}
			}

			foreach(var fkKeyValue in this.User_FKIndex)
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = clone.User_FKIndex.TryAdd(fkKeyValue.Key, new List<int>());
				}

				foreach (var pk in fkKeyValue.Value)
				{
					clone.User_FKIndex[fkKeyValue.Key].Add(pk);
				}
			}

			
			return clone;
		}

		public override IObjectsDataSet CloneDirtyObjects()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet CloneDirtyObjects(IObjectsDataSet rootDataSet)
		{
			var clone = new GOUserGroupObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.GOUserGroupObjects.Where(o => o.Value.IsDirty || o.Value.IsMarkedForDeletion))
			{
                var cloneObject = (GOUserGroupDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				while (!completed)
				{
					 completed = clone.GOUserGroupObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.GOUserGroupObjectInternalIds
				.Where(o => this.GOUserGroupObjects[o.Value].IsDirty || this.GOUserGroupObjects[o.Value].IsMarkedForDeletion))
			{
				completed = false;
				
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.GOUserGroupObjectInternalIds.TryAdd(keyValue.Key.Clone(), keyValue.Value);
				}
			}
			
			// CloneDirtyObjects is used to pass only dirty objects to server to save changes. Since indexes are not serialized, no need to clone them
            return clone;
		}

		public override IEnumerable<IDataObject> GetAllObjects()
		{
			foreach(var gOUserGroup in GOUserGroupObjects.Values)
			{
				yield return gOUserGroup; 
			}				
		}

	    public override void AddObject(IDataObject objectToAdd, bool replaceIfExists)
        {
			var existingObject = GetObject(objectToAdd);
            if (!replaceIfExists && existingObject != null)
                throw new PulpException("Object already exists");

			int newInternalId; 
			
            if (existingObject != null)
			{
                //RemoveObject(existingObject);
				if(existingObject.InternalObjectId == null)
				{
					_logEngine.LogError("Error while trying to Add Object to the GOUserGroupObjectsDataSet", "The object you are trying to add doesn't have an InternalObjectId", "GOUserGroupObjectsDataSet", null);
					throw new PulpException("Error while trying to add an object to the dataset without InternalObjectId");
				}
                newInternalId = (int) existingObject.InternalObjectId;
                objectToAdd.InternalObjectId = newInternalId;
				existingObject.CopyValuesFrom(objectToAdd, false);
			}
			else
			{
            	newInternalId = GetNextNewInternalObjectId();
				objectToAdd.InternalObjectId = newInternalId;

				 var completed = false;
				 var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOUserGroupObjects.TryAdd(newInternalId, (GOUserGroupDataObject)objectToAdd);
				}
			}
			
			if (!objectToAdd.IsNew && existingObject == null)
			{
                //The following if should not be necessary...
				var completed = false;
				if (GOUserGroupObjectInternalIds.ContainsKey(((GOUserGroupDataObject)objectToAdd).PrimaryKeysCollection))
				{
					int value;
					var count2 = 0;
					while (!completed && count2++ < 15)
					{
						completed = GOUserGroupObjectInternalIds.TryRemove(((GOUserGroupDataObject)objectToAdd).PrimaryKeysCollection, out value);
					}
				}

				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOUserGroupObjectInternalIds.TryAdd(((GOUserGroupDataObject)objectToAdd).PrimaryKeysCollection, newInternalId);
				}
			}
			// Update relations including platform as "many" side or "one" side , pk side for one to one relations
			if((objectToAdd as GOUserGroupDataObject) == null)
			{
				_logEngine.LogError("Unable to Add an object which is null", "Unable to add an object which is null", "GOUserGroupDataObject", null);
				throw new PulpException("Unexpected Error: Unable to Add an object which is Null.");
			}

			// Update the Group FK Index 
			if ((objectToAdd as GOUserGroupDataObject).GOGroupName != null)
			{
			if (!Group_FKIndex.ContainsKey((objectToAdd as GOUserGroupDataObject).GOGroupName))
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = Group_FKIndex.TryAdd((objectToAdd as GOUserGroupDataObject).GOGroupName, new List<int>());
				}
			}
				
			if (!Group_FKIndex[(objectToAdd as GOUserGroupDataObject).GOGroupName].Contains(newInternalId))
				Group_FKIndex[(objectToAdd as GOUserGroupDataObject).GOGroupName].Add(newInternalId);

            GOGroupDataObject relatedGroup;
            if ((objectToAdd as GOUserGroupDataObject)._group_NewObjectId != null)
            {
                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject() { IsNew = true, InternalObjectId = (objectToAdd as GOUserGroupDataObject)._group_NewObjectId });
            }
            else
            {
                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject((objectToAdd as GOUserGroupDataObject).GOGroupName) { IsNew = false });
            }

			if (relatedGroup != null && this.RootObjectDataSet.NotifyChanges)
                relatedGroup.NotifyPropertyChanged("UserGroupItems", new SeenObjectCollection());
			
			}
	 
			// Update the User FK Index 
			if (!User_FKIndex.ContainsKey((objectToAdd as GOUserGroupDataObject).GOUserId))
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = User_FKIndex.TryAdd((objectToAdd as GOUserGroupDataObject).GOUserId, new List<int>());
				}
			}
				
			if (!User_FKIndex[(objectToAdd as GOUserGroupDataObject).GOUserId].Contains(newInternalId))
				User_FKIndex[(objectToAdd as GOUserGroupDataObject).GOUserId].Add(newInternalId);

            GOUserDataObject relatedUser;
            if ((objectToAdd as GOUserGroupDataObject)._user_NewObjectId != null)
            {
                relatedUser = _rootObjectDataSet.GetObject(new GOUserDataObject() { IsNew = true, InternalObjectId = (objectToAdd as GOUserGroupDataObject)._user_NewObjectId });
            }
            else
            {
                relatedUser = _rootObjectDataSet.GetObject(new GOUserDataObject((objectToAdd as GOUserGroupDataObject).GOUserId) { IsNew = false });
            }

			if (relatedUser != null && this.RootObjectDataSet.NotifyChanges)
                relatedUser.NotifyPropertyChanged("UserGroupItems", new SeenObjectCollection());
			
	 
		
		}

        public override void RemoveObject(IDataObject objectToRemove)
        {
            if (GOUserGroupObjects == null)
                return;
			bool completed;			
			int? objectToRemoveInternalId;
			
			if((objectToRemove as GOUserGroupDataObject) == null)
			{
				_logEngine.LogError("Unable to remove null object", "The object you are trying to remove is null", "GOUserGroupObjectsDataSet.RemoveObject", null);
				throw new PulpException("Unable to remove Null Object.");
			}

			if (objectToRemove.IsNew)
				objectToRemoveInternalId = objectToRemove.InternalObjectId;
			else
				objectToRemoveInternalId = GOUserGroupObjectInternalIds.ContainsKey((objectToRemove as GOUserGroupDataObject).PrimaryKeysCollection) ? (int?) GOUserGroupObjectInternalIds[(objectToRemove as GOUserGroupDataObject).PrimaryKeysCollection] : null;
				
			if (objectToRemoveInternalId != null)
			{
				GOUserGroupDataObject value;
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = GOUserGroupObjects.TryRemove((int)objectToRemoveInternalId, out value);
				}

                // Reinit InternalObjectId only if the object to remove is part of the current dataset
				if (ReferenceEquals(objectToRemove.ObjectsDataSet, this._rootObjectDataSet))
					objectToRemove.InternalObjectId = null;
				
				if (!objectToRemove.IsNew)
				{
					int idvalue;
					completed = false;
					count = 0;
					while (!completed && count++ < 15)
					{
						completed = GOUserGroupObjectInternalIds.TryRemove((objectToRemove as GOUserGroupDataObject).PrimaryKeysCollection, out idvalue);
					}
				}
				
			// Delete the Group FK Index 
				if ((objectToRemove as GOUserGroupDataObject).GOGroupName != null)
				{
				if (Group_FKIndex.ContainsKey((objectToRemove as GOUserGroupDataObject).GOGroupName) && Group_FKIndex[(objectToRemove as GOUserGroupDataObject).GOGroupName].Contains((int)objectToRemoveInternalId))
				{
					Group_FKIndex[(objectToRemove as GOUserGroupDataObject).GOGroupName].Remove((int)objectToRemoveInternalId);

					if (!Group_FKIndex[(objectToRemove as GOUserGroupDataObject).GOGroupName].Any())
					{
						List<int> outvalue;
						var iscompleted = false;
						var count2 = 0;
						while (!iscompleted  && count2++ < 15)
						{
							iscompleted = Group_FKIndex.TryRemove((objectToRemove as GOUserGroupDataObject).GOGroupName, out outvalue);
						}
					}
				}
				
				GOGroupDataObject relatedGroup;
	            if ((objectToRemove as GOUserGroupDataObject)._group_NewObjectId != null)
	            {
	                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject() { IsNew = true, InternalObjectId = (objectToRemove as GOUserGroupDataObject)._group_NewObjectId });
	            }
	            else
	            {
	                relatedGroup = _rootObjectDataSet.GetObject(new GOGroupDataObject((objectToRemove as GOUserGroupDataObject).GOGroupName) { IsNew = false });
	            }

	            if (relatedGroup != null && this.RootObjectDataSet.NotifyChanges)
	                relatedGroup.NotifyPropertyChanged("UserGroupItems", new SeenObjectCollection());
				
				}
		 
			// Delete the User FK Index 
				if (User_FKIndex.ContainsKey((objectToRemove as GOUserGroupDataObject).GOUserId) && User_FKIndex[(objectToRemove as GOUserGroupDataObject).GOUserId].Contains((int)objectToRemoveInternalId))
				{
					User_FKIndex[(objectToRemove as GOUserGroupDataObject).GOUserId].Remove((int)objectToRemoveInternalId);

					if (!User_FKIndex[(objectToRemove as GOUserGroupDataObject).GOUserId].Any())
					{
						List<int> outvalue;
						var iscompleted = false;
						var count2 = 0;
						while (!iscompleted  && count2++ < 15)
						{
							iscompleted = User_FKIndex.TryRemove((objectToRemove as GOUserGroupDataObject).GOUserId, out outvalue);
						}
					}
				}
				
				GOUserDataObject relatedUser;
	            if ((objectToRemove as GOUserGroupDataObject)._user_NewObjectId != null)
	            {
	                relatedUser = _rootObjectDataSet.GetObject(new GOUserDataObject() { IsNew = true, InternalObjectId = (objectToRemove as GOUserGroupDataObject)._user_NewObjectId });
	            }
	            else
	            {
	                relatedUser = _rootObjectDataSet.GetObject(new GOUserDataObject((objectToRemove as GOUserGroupDataObject).GOUserId) { IsNew = false });
	            }

	            if (relatedUser != null && this.RootObjectDataSet.NotifyChanges)
	                relatedUser.NotifyPropertyChanged("UserGroupItems", new SeenObjectCollection());
				
		 
			}		
		}

		public override TDataObject GetObject<TDataObject>(Type objectBaseType, int internalObjectId)
        {
            return GOUserGroupObjects.ContainsKey(internalObjectId) ? GOUserGroupObjects[internalObjectId] as TDataObject : null;
        }

        public override TDataObject GetObject<TDataObject>(TDataObject objectToGet)
        {
			int? objectToGetInternalId;
			
			if (objectToGet.IsNew)
				objectToGetInternalId = objectToGet.InternalObjectId;
			else
			{
				if((objectToGet as GOUserGroupDataObject) == null)
				{
					_logEngine.LogError("Unable to get value which value is null", "The object you are trying to get doesn't have a value", "GOUserGroupObjectsDataSet", null);
					throw new PulpException("Unable to get an element which value is null.");
				}
				objectToGetInternalId = GOUserGroupObjectInternalIds.ContainsKey((objectToGet as GOUserGroupDataObject).PrimaryKeysCollection) ? (int?) GOUserGroupObjectInternalIds[(objectToGet as GOUserGroupDataObject).PrimaryKeysCollection] : null;
			}
			if (objectToGetInternalId != null)
			{
				return GOUserGroupObjects.ContainsKey((int)objectToGetInternalId) ? GOUserGroupObjects[(int)objectToGetInternalId] as TDataObject : null;
			}

			return null;
        }
		
        public override IEnumerable<IDataObject> GetObjectsMarkedForDeletion()
        {
			return GOUserGroupObjects.Values.Where(c => c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		public override IEnumerable<IDataObject> GetObjectsOutOfGraph()
        {
			return GOUserGroupObjects.Values.Where(c => !c.IncludedInGraph && !c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		
		public IEnumerable<GOUserGroupDataObject> GetUserGroupItemsForGroup(GOGroupDataObject groupInstance) 
		{
			if (groupInstance.IsNew)
            {
			
              return GOUserGroupObjects.Where(o => o.Value._group_NewObjectId != null && o.Value._group_NewObjectId == groupInstance.InternalObjectId).Select(o => o.Value);
			}
				
			if (Group_FKIndex.ContainsKey(groupInstance.Name))
			{
				return Group_FKIndex[groupInstance.Name].Where(e => GOUserGroupObjects.ContainsKey(e)).Select(e => GOUserGroupObjects[e]);
			}
			
			return new DataObjectCollection<GOUserGroupDataObject>();
		}
		 
		
		public IEnumerable<GOUserGroupDataObject> GetUserGroupItemsForUser(GOUserDataObject userInstance) 
		{
			if (userInstance.IsNew)
            {
			
              return GOUserGroupObjects.Where(o => o.Value._user_NewObjectId != null && o.Value._user_NewObjectId == userInstance.InternalObjectId).Select(o => o.Value);
			}
				
			if (User_FKIndex.ContainsKey(userInstance.Id))
			{
				return User_FKIndex[userInstance.Id].Where(e => GOUserGroupObjects.ContainsKey(e)).Select(e => GOUserGroupObjects[e]);
			}
			
			return new DataObjectCollection<GOUserGroupDataObject>();
		}
		 

        public override DataObjectCollection<TDataObject> GetRelatedObjects<TDataObject>(IDataObject rootObject, string relationName)
        {
 
 
			return null;
		}
		
        public override void Merge(IObjectsDataSet dataSetToMerge, bool updateOrginalInternalId)
        {
			var GOUserGroupDataSet = dataSetToMerge as GOUserGroupObjectsDataSet;
			if(GOUserGroupDataSet == null)
			{
				throw new PulpException("Unable to merge the current DataSet with null");
			}
            foreach (var item in GOUserGroupDataSet.GOUserGroupObjects.Values)
            {
                var oldInternalId = item.InternalObjectId;

				var objectToMerge = item.Clone(false);
                objectToMerge.InternalObjectId = null;
                objectToMerge.ObjectsDataSet = this._rootObjectDataSet;
				
				objectToMerge.IsMarkedForDeletion = item.IsMarkedForDeletion;
                
				_rootObjectDataSet.AddOrReplaceObject(objectToMerge);
                var newInternalId = objectToMerge.InternalObjectId;
                if (updateOrginalInternalId)
                    item.InternalObjectId = newInternalId;

				if (oldInternalId != null && !_rootObjectDataSet.DatasetMergingInternalIdMapping.ContainsKey((int) oldInternalId))
				{
					if(newInternalId == null)
					{
						_logEngine.LogError("Unable to merge elements in DataSet without InternalId", "The Element you are trying to merge doesn't have an internalId", "GOUserGroupObjectsDataSet", null);
						throw new PulpException("Unable to merge elements in dataset without InternalId");
					}
					var completed = false;
					var count = 0;
					while (!completed && count++ < 15)
					{
						completed = _rootObjectDataSet.DatasetMergingInternalIdMapping.TryAdd((int) oldInternalId, (int) newInternalId);
					}
				}

				MergedDataObjects.Enqueue(objectToMerge as GOUserGroupDataObject);
            }
        }
		
		public override void FinalizeMerge()
		{
			foreach(var mergedObject in MergedDataObjects)
			{
				mergedObject.UpdateRelatedInternalIds(_rootObjectDataSet.DatasetMergingInternalIdMapping);
			}
			
			ClearMergedDataObjects();
		}

		public override void ReconstructIndexes()
		{
			// Reconstruct the Group FK Index 
			Group_FKIndex = new ConcurrentDictionary< System.String, List<int>>();
				
			foreach (var item in GOUserGroupObjects.Values)
			{
				if (item.GOGroupName == null) 
					continue;				
				
				if (item.IsMarkedForDeletion)
					continue;

				var fk = item.GOGroupName;	

				if (!Group_FKIndex.ContainsKey(fk))
				{
					var iscompleted = false;
					var count2 = 0;
					while (!iscompleted && count2++ < 15)
					{
						iscompleted = Group_FKIndex.TryAdd(fk, new List<int>());
					}
				}
				if(item.InternalObjectId == null)
				{
					_logEngine.LogError("Unable to reconstruct indexes.", "An error occured while trying to reconstruct indexes", "GOUserGroupObjectsDataSet", null);
					throw new PulpException("Unable to reconstruct indexes.");
				}
					
				Group_FKIndex[fk].Add((int)item.InternalObjectId);
			}			
		 
			// Reconstruct the User FK Index 
			User_FKIndex = new ConcurrentDictionary< System.Guid, List<int>>();
				
			foreach (var item in GOUserGroupObjects.Values)
			{
				if (item.GOUserId == null) 
					continue;				
				
				if (item.IsMarkedForDeletion)
					continue;

				var fk = item.GOUserId;	

				if (!User_FKIndex.ContainsKey(fk))
				{
					var iscompleted = false;
					var count2 = 0;
					while (!iscompleted && count2++ < 15)
					{
						iscompleted = User_FKIndex.TryAdd(fk, new List<int>());
					}
				}
				if(item.InternalObjectId == null)
				{
					_logEngine.LogError("Unable to reconstruct indexes.", "An error occured while trying to reconstruct indexes", "GOUserGroupObjectsDataSet", null);
					throw new PulpException("Unable to reconstruct indexes.");
				}
					
				User_FKIndex[fk].Add((int)item.InternalObjectId);
			}			
		 
		}

		#endregion

		#region private methods
		
		private int GetNextNewInternalObjectId()
		{
			int newInternalId = _rootObjectDataSet.GetNextNewObjectId();

			// With business entity hierarchies I was seeing objects in dataset with same internal Id. Something to do with PK being the same for entities in hierarchy perhaps?
			// Anyway, it's dangeroud because means LoadParentEntity() can get stuck in infinite loop if it finds 'itself' as parent of iteself because of the internal Ids.
			// Ensure newInternalId not already in use
			while (GOUserGroupObjectInternalIds.Values.Contains(newInternalId))
			{
				newInternalId = _rootObjectDataSet.GetNextNewObjectId();
			}

			return newInternalId;
		}

		#endregion

	}	
}