////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using GenerativeObjects.Practices.ORMSupportClasses;
using GenerativeObjects.Practices.DependencyInjection;
using GenerativeObjects.Practices.Logging;
using GenerativeObjects.Practices.ExceptionHandling;
using System.Collections.Concurrent;
using GenerativeObjects.Practices.LayerSupportClasses;
using Unity;


namespace Solid.Data.DataObjects
{
	[JsonObject(MemberSerialization.OptIn)]
	public class PlaceObjectsDataSet : ObjectsDataSetBase
	{
        #region fields

        private ObjectsDataSet _rootObjectDataSet;
		private ILogEngine _logEngine = ApplicationSettings.Container.Resolve<ILogEngine>();

		// Mapping between entity primary key and data set objects collection internal id
		private ConcurrentDictionary< System.String, int> _placeObjectInternalIds = new ConcurrentDictionary< System.String, int>();
		
		// Collection holding all Place objects for current dataset
		private ConcurrentDictionary< int, PlaceDataObject> _placeObjects = new ConcurrentDictionary< int, PlaceDataObject>();

		// Temp list of merged data objects - required for merge finalization
		private ConcurrentQueue<PlaceDataObject> _mergedDataObjects;

		private ConcurrentQueue<PlaceDataObject> MergedDataObjects 
		{
			get
			{
				if (_mergedDataObjects == null)
					_mergedDataObjects = new ConcurrentQueue<PlaceDataObject>();
					
				return _mergedDataObjects;
			}
		}
		
		private void ClearMergedDataObjects()
		{
			_mergedDataObjects = null;
		}

        #endregion

		#region properties

        public ObjectsDataSet RootObjectDataSet
        {
            get { return _rootObjectDataSet; }
            set
            {
                _rootObjectDataSet = value;
            }
        }
		
		// Mapping between entity primary key and data set objects collection internal id
		public ConcurrentDictionary< System.String, int> PlaceObjectInternalIds
		{ 
			get { return _placeObjectInternalIds; }
			set { _placeObjectInternalIds = value; }
		}
		
		// Collection holding all Place objects for current dataset
		[JsonProperty(DefaultValueHandling  = DefaultValueHandling.Ignore)]
		public ConcurrentDictionary< int, PlaceDataObject> PlaceObjects
		{ 
			get { return _placeObjects; }
			set { _placeObjects = value; }
		}
		
		// Index to quickly find all Place with a given country foreign key
		public ConcurrentDictionary<System.String, List<int>> Country_FKIndex = new ConcurrentDictionary<System.String, List<int>>();
		
 
		
 
		
		#endregion
		
		#region initialization

        public PlaceObjectsDataSet(ObjectsDataSet rootObjectDataSet)
        {
            _rootObjectDataSet = rootObjectDataSet;
        }

        #endregion

		#region IObjectsDataSet implementation

		public override IObjectsDataSet Clone()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet Clone(IObjectsDataSet rootDataSet)
		{
			var clone = new PlaceObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.PlaceObjects)
			{
                var cloneObject = (PlaceDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.PlaceObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.PlaceObjectInternalIds)
			{
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.PlaceObjectInternalIds.TryAdd(keyValue.Key, keyValue.Value);
				}
			}

			foreach(var fkKeyValue in this.Country_FKIndex)
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = clone.Country_FKIndex.TryAdd(fkKeyValue.Key, new List<int>());
				}

				foreach (var pk in fkKeyValue.Value)
				{
					clone.Country_FKIndex[fkKeyValue.Key].Add(pk);
				}
			}


			
			return clone;
		}

		public override IObjectsDataSet CloneDirtyObjects()
		{
			throw new PulpException("Forbidden on sub dataset");		
		}

		public override IObjectsDataSet CloneDirtyObjects(IObjectsDataSet rootDataSet)
		{
			var clone = new PlaceObjectsDataSet(rootDataSet as ObjectsDataSet);
			bool completed;

			foreach(var keyValue in this.PlaceObjects.Where(o => o.Value.IsDirty || o.Value.IsMarkedForDeletion))
			{
                var cloneObject = (PlaceDataObject) keyValue.Value.Clone(false);
                cloneObject.InternalObjectId = keyValue.Value.InternalObjectId;
				
				completed = false;
				while (!completed)
				{
					 completed = clone.PlaceObjects.TryAdd(keyValue.Key, cloneObject);
				}
			}

			foreach(var keyValue in this.PlaceObjectInternalIds
				.Where(o => this.PlaceObjects[o.Value].IsDirty || this.PlaceObjects[o.Value].IsMarkedForDeletion))
			{
				completed = false;
				
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = clone.PlaceObjectInternalIds.TryAdd(keyValue.Key, keyValue.Value);
				}
			}
			
			// CloneDirtyObjects is used to pass only dirty objects to server to save changes. Since indexes are not serialized, no need to clone them
            return clone;
		}

		public override IEnumerable<IDataObject> GetAllObjects()
		{
			foreach(var place in PlaceObjects.Values)
			{
				yield return place; 
			}				
		}

	    public override void AddObject(IDataObject objectToAdd, bool replaceIfExists)
        {
			var existingObject = GetObject(objectToAdd);
            if (!replaceIfExists && existingObject != null)
                throw new PulpException("Object already exists");

			int newInternalId; 
			
            if (existingObject != null)
			{
                //RemoveObject(existingObject);
				if(existingObject.InternalObjectId == null)
				{
					_logEngine.LogError("Error while trying to Add Object to the PlaceObjectsDataSet", "The object you are trying to add doesn't have an InternalObjectId", "PlaceObjectsDataSet", null);
					throw new PulpException("Error while trying to add an object to the dataset without InternalObjectId");
				}
                newInternalId = (int) existingObject.InternalObjectId;
                objectToAdd.InternalObjectId = newInternalId;
				existingObject.CopyValuesFrom(objectToAdd, false);
			}
			else
			{
            	newInternalId = GetNextNewInternalObjectId();
				objectToAdd.InternalObjectId = newInternalId;

				 var completed = false;
				 var count = 0;
				while (!completed && count++ < 15)
				{
					completed = PlaceObjects.TryAdd(newInternalId, (PlaceDataObject)objectToAdd);
				}
			}
			
			if (!objectToAdd.IsNew && existingObject == null)
			{
                //The following if should not be necessary...
				var completed = false;
				if (PlaceObjectInternalIds.ContainsKey(((PlaceDataObject)objectToAdd).PrimaryKey))
				{
					int value;
					var count2 = 0;
					while (!completed && count2++ < 15)
					{
						completed = PlaceObjectInternalIds.TryRemove(((PlaceDataObject)objectToAdd).PrimaryKey, out value);
					}
				}

				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = PlaceObjectInternalIds.TryAdd(((PlaceDataObject)objectToAdd).PrimaryKey, newInternalId);
				}
			}
			// Update relations including platform as "many" side or "one" side , pk side for one to one relations
			if((objectToAdd as PlaceDataObject) == null)
			{
				_logEngine.LogError("Unable to Add an object which is null", "Unable to add an object which is null", "PlaceDataObject", null);
				throw new PulpException("Unexpected Error: Unable to Add an object which is Null.");
			}

			// Update the Country FK Index 
			if ((objectToAdd as PlaceDataObject).CountryURI != null)
			{
			if (!Country_FKIndex.ContainsKey((objectToAdd as PlaceDataObject).CountryURI))
			{
				var iscompleted = false;
				var count2 = 0;
				while (!iscompleted && count2++ < 15)
				{
					iscompleted = Country_FKIndex.TryAdd((objectToAdd as PlaceDataObject).CountryURI, new List<int>());
				}
			}
				
			if (!Country_FKIndex[(objectToAdd as PlaceDataObject).CountryURI].Contains(newInternalId))
				Country_FKIndex[(objectToAdd as PlaceDataObject).CountryURI].Add(newInternalId);

            CountryDataObject relatedCountry;
            if ((objectToAdd as PlaceDataObject)._country_NewObjectId != null)
            {
                relatedCountry = _rootObjectDataSet.GetObject(new CountryDataObject() { IsNew = true, InternalObjectId = (objectToAdd as PlaceDataObject)._country_NewObjectId });
            }
            else
            {
                relatedCountry = _rootObjectDataSet.GetObject(new CountryDataObject((objectToAdd as PlaceDataObject).CountryURI) { IsNew = false });
            }

			if (relatedCountry != null && this.RootObjectDataSet.NotifyChanges)
                relatedCountry.NotifyPropertyChanged("PlaceItems", new SeenObjectCollection());
			
			}
	 
	 
		
		}

        public override void RemoveObject(IDataObject objectToRemove)
        {
            if (PlaceObjects == null)
                return;
			bool completed;			
			int? objectToRemoveInternalId;
			
			if((objectToRemove as PlaceDataObject) == null)
			{
				_logEngine.LogError("Unable to remove null object", "The object you are trying to remove is null", "PlaceObjectsDataSet.RemoveObject", null);
				throw new PulpException("Unable to remove Null Object.");
			}

			if (objectToRemove.IsNew)
				objectToRemoveInternalId = objectToRemove.InternalObjectId;
			else
				objectToRemoveInternalId = PlaceObjectInternalIds.ContainsKey((objectToRemove as PlaceDataObject).PrimaryKey) ? (int?) PlaceObjectInternalIds[(objectToRemove as PlaceDataObject).PrimaryKey] : null;
				
			if (objectToRemoveInternalId != null)
			{
				PlaceDataObject value;
				completed = false;
				var count = 0;
				while (!completed && count++ < 15)
				{
					completed = PlaceObjects.TryRemove((int)objectToRemoveInternalId, out value);
				}

                // Reinit InternalObjectId only if the object to remove is part of the current dataset
				if (ReferenceEquals(objectToRemove.ObjectsDataSet, this._rootObjectDataSet))
					objectToRemove.InternalObjectId = null;
				
				if (!objectToRemove.IsNew)
				{
					int idvalue;
					completed = false;
					count = 0;
					while (!completed && count++ < 15)
					{
						completed = PlaceObjectInternalIds.TryRemove((objectToRemove as PlaceDataObject).PrimaryKey, out idvalue);
					}
				}
				
			// Delete the Country FK Index 
				if ((objectToRemove as PlaceDataObject).CountryURI != null)
				{
				if (Country_FKIndex.ContainsKey((objectToRemove as PlaceDataObject).CountryURI) && Country_FKIndex[(objectToRemove as PlaceDataObject).CountryURI].Contains((int)objectToRemoveInternalId))
				{
					Country_FKIndex[(objectToRemove as PlaceDataObject).CountryURI].Remove((int)objectToRemoveInternalId);

					if (!Country_FKIndex[(objectToRemove as PlaceDataObject).CountryURI].Any())
					{
						List<int> outvalue;
						var iscompleted = false;
						var count2 = 0;
						while (!iscompleted  && count2++ < 15)
						{
							iscompleted = Country_FKIndex.TryRemove((objectToRemove as PlaceDataObject).CountryURI, out outvalue);
						}
					}
				}
				
				CountryDataObject relatedCountry;
	            if ((objectToRemove as PlaceDataObject)._country_NewObjectId != null)
	            {
	                relatedCountry = _rootObjectDataSet.GetObject(new CountryDataObject() { IsNew = true, InternalObjectId = (objectToRemove as PlaceDataObject)._country_NewObjectId });
	            }
	            else
	            {
	                relatedCountry = _rootObjectDataSet.GetObject(new CountryDataObject((objectToRemove as PlaceDataObject).CountryURI) { IsNew = false });
	            }

	            if (relatedCountry != null && this.RootObjectDataSet.NotifyChanges)
	                relatedCountry.NotifyPropertyChanged("PlaceItems", new SeenObjectCollection());
				
				}
		 
		 
			}		
		}

		public override TDataObject GetObject<TDataObject>(Type objectBaseType, int internalObjectId)
        {
            return PlaceObjects.ContainsKey(internalObjectId) ? PlaceObjects[internalObjectId] as TDataObject : null;
        }

        public override TDataObject GetObject<TDataObject>(TDataObject objectToGet)
        {
			int? objectToGetInternalId;
			
			if (objectToGet.IsNew)
				objectToGetInternalId = objectToGet.InternalObjectId;
			else
			{
				if((objectToGet as PlaceDataObject) == null)
				{
					_logEngine.LogError("Unable to get value which value is null", "The object you are trying to get doesn't have a value", "PlaceObjectsDataSet", null);
					throw new PulpException("Unable to get an element which value is null.");
				}
				objectToGetInternalId = PlaceObjectInternalIds.ContainsKey((objectToGet as PlaceDataObject).PrimaryKey) ? (int?) PlaceObjectInternalIds[(objectToGet as PlaceDataObject).PrimaryKey] : null;
			}
			if (objectToGetInternalId != null)
			{
				return PlaceObjects.ContainsKey((int)objectToGetInternalId) ? PlaceObjects[(int)objectToGetInternalId] as TDataObject : null;
			}

			return null;
        }
		
        public override IEnumerable<IDataObject> GetObjectsMarkedForDeletion()
        {
			return PlaceObjects.Values.Where(c => c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		public override IEnumerable<IDataObject> GetObjectsOutOfGraph()
        {
			return PlaceObjects.Values.Where(c => !c.IncludedInGraph && !c.IsMarkedForDeletion).Cast<IDataObject>();
        }

		
		public IEnumerable<PlaceDataObject> GetPlaceItemsForCountry(CountryDataObject countryInstance) 
		{
			if (countryInstance.IsNew)
            {
			
              return PlaceObjects.Where(o => o.Value._country_NewObjectId != null && o.Value._country_NewObjectId == countryInstance.InternalObjectId).Select(o => o.Value);
			}
				
			if (Country_FKIndex.ContainsKey(countryInstance.URI))
			{
				return Country_FKIndex[countryInstance.URI].Where(e => PlaceObjects.ContainsKey(e)).Select(e => PlaceObjects[e]);
			}
			
			return new DataObjectCollection<PlaceDataObject>();
		}
		 
		 

        public override DataObjectCollection<TDataObject> GetRelatedObjects<TDataObject>(IDataObject rootObject, string relationName)
        {
 
			if (relationName == "PlaceToLocationItems")
            {
				IEnumerable< PlaceToLocationDataObject> relatedObjects;					
				relatedObjects = _rootObjectDataSet.PlaceToLocationObjectsDataSet.GetPlaceToLocationItemsForPlace(rootObject as PlaceDataObject);
				
				var result = new DataObjectCollection<TDataObject>();
				
				if (relatedObjects != null)
				{
                    result.NotifyChanges = false;

					foreach(var relatedObject in relatedObjects)
						result.Add(relatedObject as TDataObject);

                    result.NotifyChanges = true;
				}	
				
                result.ObjectsDataSet = this._rootObjectDataSet;

				return result;
			}
 
			return null;
		}
		
        public override void Merge(IObjectsDataSet dataSetToMerge, bool updateOrginalInternalId)
        {
			var PlaceDataSet = dataSetToMerge as PlaceObjectsDataSet;
			if(PlaceDataSet == null)
			{
				throw new PulpException("Unable to merge the current DataSet with null");
			}
            foreach (var item in PlaceDataSet.PlaceObjects.Values)
            {
                var oldInternalId = item.InternalObjectId;

				var objectToMerge = item.Clone(false);
                objectToMerge.InternalObjectId = null;
                objectToMerge.ObjectsDataSet = this._rootObjectDataSet;
				
				objectToMerge.IsMarkedForDeletion = item.IsMarkedForDeletion;
                
				_rootObjectDataSet.AddOrReplaceObject(objectToMerge);
                var newInternalId = objectToMerge.InternalObjectId;
                if (updateOrginalInternalId)
                    item.InternalObjectId = newInternalId;

				if (oldInternalId != null && !_rootObjectDataSet.DatasetMergingInternalIdMapping.ContainsKey((int) oldInternalId))
				{
					if(newInternalId == null)
					{
						_logEngine.LogError("Unable to merge elements in DataSet without InternalId", "The Element you are trying to merge doesn't have an internalId", "PlaceObjectsDataSet", null);
						throw new PulpException("Unable to merge elements in dataset without InternalId");
					}
					var completed = false;
					var count = 0;
					while (!completed && count++ < 15)
					{
						completed = _rootObjectDataSet.DatasetMergingInternalIdMapping.TryAdd((int) oldInternalId, (int) newInternalId);
					}
				}

				MergedDataObjects.Enqueue(objectToMerge as PlaceDataObject);
            }
        }
		
		public override void FinalizeMerge()
		{
			foreach(var mergedObject in MergedDataObjects)
			{
				mergedObject.UpdateRelatedInternalIds(_rootObjectDataSet.DatasetMergingInternalIdMapping);
			}
			
			ClearMergedDataObjects();
		}

		public override void ReconstructIndexes()
		{
			// Reconstruct the Country FK Index 
			Country_FKIndex = new ConcurrentDictionary< System.String, List<int>>();
				
			foreach (var item in PlaceObjects.Values)
			{
				if (item.CountryURI == null) 
					continue;				
				
				if (item.IsMarkedForDeletion)
					continue;

				var fk = item.CountryURI;	

				if (!Country_FKIndex.ContainsKey(fk))
				{
					var iscompleted = false;
					var count2 = 0;
					while (!iscompleted && count2++ < 15)
					{
						iscompleted = Country_FKIndex.TryAdd(fk, new List<int>());
					}
				}
				if(item.InternalObjectId == null)
				{
					_logEngine.LogError("Unable to reconstruct indexes.", "An error occured while trying to reconstruct indexes", "PlaceObjectsDataSet", null);
					throw new PulpException("Unable to reconstruct indexes.");
				}
					
				Country_FKIndex[fk].Add((int)item.InternalObjectId);
			}			
		 
		 
		}

		#endregion

		#region private methods
		
		private int GetNextNewInternalObjectId()
		{
			int newInternalId = _rootObjectDataSet.GetNextNewObjectId();

			// With business entity hierarchies I was seeing objects in dataset with same internal Id. Something to do with PK being the same for entities in hierarchy perhaps?
			// Anyway, it's dangeroud because means LoadParentEntity() can get stuck in infinite loop if it finds 'itself' as parent of iteself because of the internal Ids.
			// Ensure newInternalId not already in use
			while (PlaceObjectInternalIds.Values.Contains(newInternalId))
			{
				newInternalId = _rootObjectDataSet.GetNextNewObjectId();
			}

			return newInternalId;
		}

		#endregion

	}	
}