////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GenerativeObjects.Practices;

namespace Solid.Data.DataObjects
{
	public enum PlaceTypesEnum : int
	{
		Place = 0,
		Country = 1,
	}

    public static class PlaceTypesEnumDisplayNames
    {
        public static readonly List<EnumDisplayString<PlaceTypesEnum>> Items
            = new List<EnumDisplayString<PlaceTypesEnum>>
                  {
					new EnumDisplayString<PlaceTypesEnum>(PlaceTypesEnum.Place, "Place (monument, historical place, park etc.)"),
					new EnumDisplayString<PlaceTypesEnum>(PlaceTypesEnum.Country, "Country"),
	              };
    }
}