////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GenerativeObjects.Practices.MVPVM;
using Solid.Data.DataObjects;
using GenerativeObjects.Practices.ORMSupportClasses;

namespace Solid.BusinessLayer.Components.Client
{
}
