////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 

(function () {
	// 
	Solid.Web.Controllers.CountryPageController = function(applicationController) {
		var self = this;
		this.subscriptions = [];
		// store all subscriptions in this array, to unsubscribe on release.
		
		this._objectType = "CountryPage";

		this.applicationController = applicationController;
		this.ObjectsDataSet = applicationController.ObjectsDataSet;
		this.contextId = [this.applicationController.getNextContextId()];
		this.customController = undefined;

		// Integrate custom code if any
		if (Solid.Web.Controllers.CountryPageControllerCustom !== undefined) {
		    this.customController = new Solid.Web.Controllers.CountryPageControllerCustom(self);
		};

		this.pageTitle = ko.observable("Country Details Page");

		// Initialize View Models and Data Stores
		
			this.CountryViewModel = new Solid.Web.ViewModels.CountryFormViewModel(this, $("#CountryFormControl"), null, null, this.contextId);		
	
		// Attach to view models events
		this.subscriptions.push(this.CountryViewModel.StatusData.IsBusy.subscribe( function (newValue) { self.OnCountryViewModelIsBusyChanged(newValue); }));
		
		this.IsInEditMode = function() {

			return  (self.CountryViewModel.StatusData.DisplayMode && self.CountryViewModel.StatusData.DisplayMode() == 'edit');
		};


		// Events Handlers
		this.OnCountryViewModelIsBusyChanged = function (newValue) {
		};

		this.initialize = function() {
			if (Solid.Web.Controllers.Custom && Solid.Web.Controllers.Custom.getPageTitle) {
				self.pageTitle(Solid.Web.Controllers.Custom.getPageTitle(self));
			}

			var partsCount = location.hash.split("/").length;
			var lasttagindex = 0;
			if (partsCount == 5) {
				var hash = window.location.hash;
				var allPksValid = true;
				lasttagindex = hash.lastIndexOf('/');
				var pk1 = hash.substring(lasttagindex + 1).split(new RegExp("#", "g"))[0];
				
				if(allPksValid) {
					var objectToLoad = new Solid.Web.Model.DataObjects.CountryObject();
					objectToLoad.Data.URI(pk1);	
					self.CountryViewModel.LoadCountry(objectToLoad);	
				}
			}
			else {
					self.CountryViewModel.CreateNew();
			}
				
	
			// Call custom initialize if defined
			if (self.customController !== undefined && self.customController.initialize !== undefined) {
			    self.customController.initialize();
			}
		};
		this.initialize();



		this.release = function() {
			// unsubscribe
			for(var i = 0;i <  self.subscriptions.length;i++) {
				self.subscriptions[i].dispose();
			}
			self.subscriptions = [];
			self.ObjectsDataSet.cleanContext(self.contextId);
			
			self.CountryViewModel.release();
			self.CountryViewModel = null;
		};


		return self;
	};		
	
	if (window.ApplicationSourceHandler)
		window.ApplicationSourceHandler.onSourceLoaded("/Controllers/CountryPageController.js");
} ());
