////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
//////////////////////////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using System.Web;
using GenerativeObjects.Practices.LayerSupportClasses.ServiceLayer;
using GenerativeObjects.Practices.LayerSupportClasses.ServiceLayer.Http;
using Solid.Data.DataObjects;
using Unity;
using GenerativeObjects.Practices.LayerSupportClasses;


namespace Solid.ServiceLayer.WebHandlers
{
    public class DataApiHandler : ApiHandler
    {
        public override void DoProcessRequest(HttpContext context)
        {
			ApiRequest request = new ApiRequest(context);
            ApplicationSettings.Container.Resolve<IEntityApiHandler>(request.Target.ToLower() + "apihandler").DoProcessRequest(request);
        }		
		       
        public override bool IsReusable
        {
            get { return true; }
        }
	}
} 