////////////////////////////////////////////////////////////////////////////////////////////
// This is Generated Code
// You should not modify this code as it may be overwritten. Use Partial classes instead
// Generated By Generative Objects  
////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Linq;
using System.Collections.Generic;
using GenerativeObjects.Practices.ORMSupportClasses;
using GenerativeObjects.Practices.ORMSupportClasses.NHibernate;

namespace Solid.Data.DataObjects
{
	////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	// Bridge DataObject -> ORMEntity
	//
	////////////////////////////////////////////////////////////////////////////////////////////////////////
	public partial class GOGroupRoleDataObject
	{
		public override IORMEntity ToORMEntity()
		{
			var session = NHibernateSessionController.GetCurrentSession();

			var result = new ORMGOGroupRole(); 
			CopyTo(result, session);

			// Ensure no copy of result (instance with same key) in session
			Evict(result, session);

			return result;
		}

		protected void CopyTo(ORMGOGroupRole x, NHibernate.ISession session)
		{
			x.GORoleName = this.Role != null ? this.Role.Name : GORoleName; 
				
			x.Group = this.Group != null ? session.Load<ORMGOGroup>(this.Group.Name) : (this.GOGroupName != null ? session.Load<ORMGOGroup>(this.GOGroupName) : null);
			x.GOGroupName = this.Group != null ? this.Group.Name : GOGroupName; 
		}
 
		private void Evict(ORMGOGroupRole result, NHibernate.ISession session)
		{
			foreach (var entity in session.GetSessionImplementation().PersistenceContext.EntitiesByKey.Values.ToArray())
			{
				var evictee = entity as ORMGOGroupRole;

				if (evictee != null && evictee.CompositeIdentity.Equals(result.CompositeIdentity))
				{
					session.Evict(evictee);
				}
			}
		}

	}
}